package Reto;


public class Reto02 extends javax.swing.JFrame {

    private double bonificacion=0.0;
    private double descuento=0.0;
    private double pago_total=0.0;
    
    public Reto02() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSueldo = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtECivil = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtImprimir = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("INFORMACIÓN\nBonificacion:\nTipo                    Masculino \tFemenino\nSoltero\t8%\t10%\nCasado\t10%\t12%\n\nDescuento:\nTipo\tMasculino\tFemenino\nSoltero\t6%\t5%\nCasado\t4%\t3%");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Sueldo:");

        jLabel2.setText("Sexo:");

        jLabel3.setText("Estado Civil");

        txtImprimir.setColumns(20);
        txtImprimir.setRows(5);
        jScrollPane2.setViewportView(txtImprimir);

        jLabel4.setText("Reporte:");

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtECivil, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnEnviar)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtECivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnEnviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        //ENTRADA
        double sueldo= Double.parseDouble(txtSueldo.getText());
        String sexo= txtSexo.getText();
        String eCivil= txtECivil.getText();
        
        System.out.println(sueldo);
        System.out.println(sexo);
        System.out.println(eCivil);
        
        //PROCESO
        this.calcularBonificacion(sexo, eCivil,sueldo);
        this.calcularDescuento(sexo,eCivil,sueldo,bonificacion);
        this.calcularPagoTotal(descuento,bonificacion,sueldo);
            
        //SALIDA
        txtImprimir.setText(null);
        txtImprimir.append("Bonificacion: S/"+bonificacion);
        txtImprimir.append("\nDescuento: S/"+descuento);
        txtImprimir.append("\nPago Total: S/"+pago_total);

    }//GEN-LAST:event_btnEnviarActionPerformed

     //procedimiento
    public void calcularBonificacion(String sexo, String eCivil,double sueldo)
    {
        if (sexo.equals("Masculino") && eCivil.equals("Soltero")) {
           bonificacion = sueldo * 0.08;
       } else if (sexo.equals("Femenino") && eCivil.equals("Soltero")) {
           bonificacion = sueldo * 0.1;
       } else if (sexo.equals("Masculino") && eCivil.equals("Casado")) {
           bonificacion = sueldo * 0.1;
       } else if (sexo.equals("Femenino") && eCivil.equals("Casado")) {
           bonificacion = sueldo * 0.12;
       }
    }
    
    //procedimiento
    public void calcularDescuento(String sexo, String eCivil,double sueldo,double bonificacion)
    {
        descuento= sueldo+bonificacion;
        
        if(sexo.equals("Masculino") && eCivil.equals("Soltero"))
       {
           descuento = descuento *0.06;
       }else if(sexo.equals("Femenino") && eCivil.equals("Soltero")) 
       {
            descuento = descuento *0.05;
       }else if(sexo.equals("Masculino") && eCivil.equals("Casado"))
       {
            descuento = descuento *0.04;
       }else if(sexo.equals("Femenino") && eCivil.equals("Casado"))
       {
            descuento = descuento *0.03;
       }
        
    }
    
    public void calcularPagoTotal(double descuento, double bonificacion,double sueldo)
    {
        pago_total=descuento+bonificacion+sueldo;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reto02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reto02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reto02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reto02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reto02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtECivil;
    private javax.swing.JTextArea txtImprimir;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtSueldo;
    // End of variables declaration//GEN-END:variables
}
